---
### group_vars/CA1_L3_LEAFS.yml

type: l2leaf     # Must be leaf

# IDF - Leaf Switches
# ['spine', 'l3leaf', 'l2leaf', 'l3spine', 'l2spine', 'super-spine', 'overlay-controller', 'wan_router', 'wan_rr', 'p', 'pe', 'rr']
l2leaf:
  defaults:
    platform: vEOS-lab
    mlag_peer_ipv4_pool: 169.254.0.0/24
    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
    inband_mgmt_subnet: 10.1.100.0/24
    inband_mgmt_vlan: 1000
    mlag: true
    mlag_interfaces: 
      - Ethernet7
      - Ethernet8
    uplink_switches: 
      - CA1-SPINE1
      - CA1-SPINE2
    uplink_interfaces: 
      - Ethernet1
      - Ethernet2

  node_groups:
    - group: CA1_L3_LEAFS_IDF1
      filter:
        tags: [ "110", "111", "112" ]
      nodes:
        - name: CA1-LEAF1A
          id: 3
          mgmt_ip: 192.168.223.101/24
          uplink_switch_interfaces: 
            - Ethernet1
            - Ethernet1

        - name: CA1-LEAF1B
          id: 4
          mgmt_ip: 192.168.223.102/24
          uplink_switch_interfaces: 
            - Ethernet2
            - Ethernet2
